### ISSUE TITLE
Build Issue - no matching function for call to `transform_reduce`

### ISSUE THREAD

**Issue by michael-etzkorn** [chipsalliance/verible#1347]
**Describe the bug**

Apologies for the tag. This is the closest I could find on the template. 

The issue seems similar to https://github.com/chipsalliance/verible/issues/611. 

glibc version - 2.17
gcc version - 9.2.0
OS - CentOS 7.9.2009 (which might be the problem here)

```
ERROR: verible/verilog/formatting/BUILD:41:11: Compiling verilog/formatting/tree_unwrapper.cc failed: (Exit 1): gcc failed: error executing command /usr/local/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 34 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./common/formatting/tree_unwrapper.h:31,
                 from ./verilog/formatting/tree_unwrapper.h:26,
                 from verilog/formatting/tree_unwrapper.cc:15:
./common/util/tree_operations.h: In instantiation of 'void verible::FlattenOnlyChildrenWithChildren(T&, std::vector<long unsigned int>*) [with T = verible::VectorTree<verible::UnwrappedLine>; std::enable_if_t<(verible::TreeNodeTraits<T>::available && (! is_const_v<T>))>* <anonymous> = 0]':
verilog/formatting/tree_unwrapper.cc:2512:79:   required from here
./common/util/tree_operations.h:761:55: error: no matching function for call to 'transform_reduce(verible::ContainerProxyBase<verible::VectorTree<verible::UnwrappedLine>::ChildrenList, std::vector<verible::VectorTree<verible::UnwrappedLine>, std::allocator<verible::VectorTree<verible::UnwrappedLine> > > >::iterator, verible::ContainerProxyBase<verible::VectorTree<verible::UnwrappedLine>::ChildrenList, std::vector<verible::VectorTree<verible::UnwrappedLine>, std::allocator<verible::VectorTree<verible::UnwrappedLine> > > >::iterator, int, std::plus<void>, verible::FlattenOnlyChildrenWithChildren(T&, std::vector<long unsigned int>*) [with T = verible::VectorTree<verible::UnwrappedLine>; std::enable_if_t<(verible::TreeNodeTraits<T>::available && (! is_const_v<T>))>* <anonymous> = 0]::<lambda(const verible::VectorTree<verible::UnwrappedLine>&)>)'
  761 |   const int new_children_count = std::transform_reduce(
      |                                  ~~~~~~~~~~~~~~~~~~~~~^
  762 |       node.Children().begin(), node.Children().end(), 0, std::plus<>(),
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  763 |       [](const T& gc) {
      |       ~~~~~~~~~~~~~~~~~
  764 |         return std::max<size_t>(std::size(gc.Children()), 1u);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  765 |       });
      |       ~~
In file included from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/numeric:229,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/random.tcc:33,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/random:51,
                 from external/com_google_absl/absl/random/random.h:34,
                 from ./common/util/interval_set.h:24,
                 from ./common/strings/position.h:21,
                 from ./common/formatting/format_token.h:24,
                 from ./verilog/formatting/tree_unwrapper.h:24,
                 from verilog/formatting/tree_unwrapper.cc:15:
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_numeric_defs.h:35:1: note: candidate: 'template<class _ExecutionPolicy, class _ForwardIterator1, class _ForwardIterator2, class _Tp> __pstl::__internal::__enable_if_execution_policy<_ExecutionPolicy, _ForwardIterator2> std::transform_reduce(_ExecutionPolicy&&, _ForwardIterator1, _ForwardIterator1, _ForwardIterator2, _Tp)'
   35 | transform_reduce(_ExecutionPolicy&& __exec, _ForwardIterator1 __first1, _ForwardIterator1 __last1,
      | ^~~~~~~~~~~~~~~~
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_numeric_defs.h:35:1: note:   template argument deduction/substitution failed:
In file included from ./common/formatting/tree_unwrapper.h:31,
                 from ./verilog/formatting/tree_unwrapper.h:26,
                 from verilog/formatting/tree_unwrapper.cc:15:
./common/util/tree_operations.h:761:55: note:   deduced conflicting types for parameter '_ForwardIterator1' ('__gnu_cxx::__normal_iterator<verible::VectorTree<verible::UnwrappedLine>*, std::vector<verible::VectorTree<verible::UnwrappedLine>, std::allocator<verible::VectorTree<verible::UnwrappedLine> > > >' and 'int')
  761 |   const int new_children_count = std::transform_reduce(
      |                                  ~~~~~~~~~~~~~~~~~~~~~^
  762 |       node.Children().begin(), node.Children().end(), 0, std::plus<>(),
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  763 |       [](const T& gc) {
      |       ~~~~~~~~~~~~~~~~~
  764 |         return std::max<size_t>(std::size(gc.Children()), 1u);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  765 |       });
      |       ~~
In file included from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/numeric:229,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/random.tcc:33,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/random:51,
                 from external/com_google_absl/absl/random/random.h:34,
                 from ./common/util/interval_set.h:24,
                 from ./common/strings/position.h:21,
                 from ./common/formatting/format_token.h:24,
                 from ./verilog/formatting/tree_unwrapper.h:24,
                 from verilog/formatting/tree_unwrapper.cc:15:
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_numeric_defs.h:41:1: note: candidate: 'template<class _ExecutionPolicy, class _ForwardIterator1, class _ForwardIterator2, class _Tp, class _BinaryOperation1, class _BinaryOperation2> __pstl::__internal::__enable_if_execution_policy<_ExecutionPolicy, _ForwardIterator2> std::transform_reduce(_ExecutionPolicy&&, _ForwardIterator1, _ForwardIterator1, _ForwardIterator2, _Tp, _BinaryOperation1, _BinaryOperation2)'
   41 | transform_reduce(_ExecutionPolicy&& __exec, _ForwardIterator1 __first1, _ForwardIterator1 __last1,
      | ^~~~~~~~~~~~~~~~
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_numeric_defs.h:41:1: note:   template argument deduction/substitution failed:
In file included from ./common/formatting/tree_unwrapper.h:31,
                 from ./verilog/formatting/tree_unwrapper.h:26,
                 from verilog/formatting/tree_unwrapper.cc:15:
./common/util/tree_operations.h:761:55: note:   deduced conflicting types for parameter '_ForwardIterator1' ('__gnu_cxx::__normal_iterator<verible::VectorTree<verible::UnwrappedLine>*, std::vector<verible::VectorTree<verible::UnwrappedLine>, std::allocator<verible::VectorTree<verible::UnwrappedLine> > > >' and 'int')
  761 |   const int new_children_count = std::transform_reduce(
      |                                  ~~~~~~~~~~~~~~~~~~~~~^
  762 |       node.Children().begin(), node.Children().end(), 0, std::plus<>(),
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  763 |       [](const T& gc) {
      |       ~~~~~~~~~~~~~~~~~
  764 |         return std::max<size_t>(std::size(gc.Children()), 1u);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  765 |       });
      |       ~~
In file included from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/numeric:229,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/random.tcc:33,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/random:51,
                 from external/com_google_absl/absl/random/random.h:34,
                 from ./common/util/interval_set.h:24,
                 from ./common/strings/position.h:21,
                 from ./common/formatting/format_token.h:24,
                 from ./verilog/formatting/tree_unwrapper.h:24,
                 from verilog/formatting/tree_unwrapper.cc:15:
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_numeric_defs.h:47:1: note: candidate: 'template<class _ExecutionPolicy, class _ForwardIterator, class _Tp, class _BinaryOperation, class _UnaryOperation> __pstl::__internal::__enable_if_execution_policy<_ExecutionPolicy, _ForwardIterator2> std::transform_reduce(_ExecutionPolicy&&, _ForwardIterator, _ForwardIterator, _Tp, _BinaryOperation, _UnaryOperation)'
   47 | transform_reduce(_ExecutionPolicy&& __exec, _ForwardIterator __first, _ForwardIterator __last, _Tp __init,
      | ^~~~~~~~~~~~~~~~
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_numeric_defs.h:47:1: note:   template argument deduction/substitution failed:
In file included from ./common/formatting/tree_unwrapper.h:31,
                 from ./verilog/formatting/tree_unwrapper.h:26,
                 from verilog/formatting/tree_unwrapper.cc:15:
./common/util/tree_operations.h:761:55: note:   deduced conflicting types for parameter '_ForwardIterator' ('__gnu_cxx::__normal_iterator<verible::VectorTree<verible::UnwrappedLine>*, std::vector<verible::VectorTree<verible::UnwrappedLine>, std::allocator<verible::VectorTree<verible::UnwrappedLine> > > >' and 'int')
  761 |   const int new_children_count = std::transform_reduce(
      |                                  ~~~~~~~~~~~~~~~~~~~~~^
  762 |       node.Children().begin(), node.Children().end(), 0, std::plus<>(),
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  763 |       [](const T& gc) {
      |       ~~~~~~~~~~~~~~~~~
  764 |         return std::max<size_t>(std::size(gc.Children()), 1u);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  765 |       });
      |       ~~
./common/util/tree_operations.h: In instantiation of 'void verible::FlattenOnce(T&) [with T = verible::VectorTree<verible::UnwrappedLine>; std::enable_if_t<(verible::TreeNodeTraits<T>::available && (! is_const_v<T>))>* <anonymous> = 0]':
verilog/formatting/tree_unwrapper.cc:2686:30:   required from here
./common/util/tree_operations.h:729:56: error: no matching function for call to 'transform_reduce(verible::ContainerProxyBase<verible::VectorTree<verible::UnwrappedLine>::ChildrenList, std::vector<verible::VectorTree<verible::UnwrappedLine>, std::allocator<verible::VectorTree<verible::UnwrappedLine> > > >::iterator, verible::ContainerProxyBase<verible::VectorTree<verible::UnwrappedLine>::ChildrenList, std::vector<verible::VectorTree<verible::UnwrappedLine>, std::allocator<verible::VectorTree<verible::UnwrappedLine> > > >::iterator, int, std::plus<void>, verible::FlattenOnce(T&) [with T = verible::VectorTree<verible::UnwrappedLine>; std::enable_if_t<(verible::TreeNodeTraits<T>::available && (! is_const_v<T>))>* <anonymous> = 0]::<lambda(const verible::VectorTree<verible::UnwrappedLine>&)>)'
  729 |   const int grandchildren_count = std::transform_reduce(
      |                                   ~~~~~~~~~~~~~~~~~~~~~^
  730 |       node.Children().begin(), node.Children().end(), 0, std::plus<>(),
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  731 |       [](const T& gc) { return std::size(gc.Children()); });
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/numeric:229,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/random.tcc:33,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/random:51,
                 from external/com_google_absl/absl/random/random.h:34,
                 from ./common/util/interval_set.h:24,
                 from ./common/strings/position.h:21,
                 from ./common/formatting/format_token.h:24,
                 from ./verilog/formatting/tree_unwrapper.h:24,
                 from verilog/formatting/tree_unwrapper.cc:15:
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_numeric_defs.h:35:1: note: candidate: 'template<class _ExecutionPolicy, class _ForwardIterator1, class _ForwardIterator2, class _Tp> __pstl::__internal::__enable_if_execution_policy<_ExecutionPolicy, _ForwardIterator2> std::transform_reduce(_ExecutionPolicy&&, _ForwardIterator1, _ForwardIterator1, _ForwardIterator2, _Tp)'
   35 | transform_reduce(_ExecutionPolicy&& __exec, _ForwardIterator1 __first1, _ForwardIterator1 __last1,
      | ^~~~~~~~~~~~~~~~
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_numeric_defs.h:35:1: note:   template argument deduction/substitution failed:
In file included from ./common/formatting/tree_unwrapper.h:31,
                 from ./verilog/formatting/tree_unwrapper.h:26,
                 from verilog/formatting/tree_unwrapper.cc:15:
./common/util/tree_operations.h:729:56: note:   deduced conflicting types for parameter '_ForwardIterator1' ('__gnu_cxx::__normal_iterator<verible::VectorTree<verible::UnwrappedLine>*, std::vector<verible::VectorTree<verible::UnwrappedLine>, std::allocator<verible::VectorTree<verible::UnwrappedLine> > > >' and 'int')
  729 |   const int grandchildren_count = std::transform_reduce(
      |                                   ~~~~~~~~~~~~~~~~~~~~~^
  730 |       node.Children().begin(), node.Children().end(), 0, std::plus<>(),
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  731 |       [](const T& gc) { return std::size(gc.Children()); });
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/numeric:229,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/random.tcc:33,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/random:51,
                 from external/com_google_absl/absl/random/random.h:34,
                 from ./common/util/interval_set.h:24,
                 from ./common/strings/position.h:21,
                 from ./common/formatting/format_token.h:24,
                 from ./verilog/formatting/tree_unwrapper.h:24,
                 from verilog/formatting/tree_unwrapper.cc:15:
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_numeric_defs.h:41:1: note: candidate: 'template<class _ExecutionPolicy, class _ForwardIterator1, class _ForwardIterator2, class _Tp, class _BinaryOperation1, class _BinaryOperation2> __pstl::__internal::__enable_if_execution_policy<_ExecutionPolicy, _ForwardIterator2> std::transform_reduce(_ExecutionPolicy&&, _ForwardIterator1, _ForwardIterator1, _ForwardIterator2, _Tp, _BinaryOperation1, _BinaryOperation2)'
   41 | transform_reduce(_ExecutionPolicy&& __exec, _ForwardIterator1 __first1, _ForwardIterator1 __last1,
      | ^~~~~~~~~~~~~~~~
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_numeric_defs.h:41:1: note:   template argument deduction/substitution failed:
In file included from ./common/formatting/tree_unwrapper.h:31,
                 from ./verilog/formatting/tree_unwrapper.h:26,
                 from verilog/formatting/tree_unwrapper.cc:15:
./common/util/tree_operations.h:729:56: note:   deduced conflicting types for parameter '_ForwardIterator1' ('__gnu_cxx::__normal_iterator<verible::VectorTree<verible::UnwrappedLine>*, std::vector<verible::VectorTree<verible::UnwrappedLine>, std::allocator<verible::VectorTree<verible::UnwrappedLine> > > >' and 'int')
  729 |   const int grandchildren_count = std::transform_reduce(
      |                                   ~~~~~~~~~~~~~~~~~~~~~^
  730 |       node.Children().begin(), node.Children().end(), 0, std::plus<>(),
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  731 |       [](const T& gc) { return std::size(gc.Children()); });
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/numeric:229,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/random.tcc:33,
                 from /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/random:51,
                 from external/com_google_absl/absl/random/random.h:34,
                 from ./common/util/interval_set.h:24,
                 from ./common/strings/position.h:21,
                 from ./common/formatting/format_token.h:24,
                 from ./verilog/formatting/tree_unwrapper.h:24,
                 from verilog/formatting/tree_unwrapper.cc:15:
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_numeric_defs.h:47:1: note: candidate: 'template<class _ExecutionPolicy, class _ForwardIterator, class _Tp, class _BinaryOperation, class _UnaryOperation> __pstl::__internal::__enable_if_execution_policy<_ExecutionPolicy, _ForwardIterator2> std::transform_reduce(_ExecutionPolicy&&, _ForwardIterator, _ForwardIterator, _Tp, _BinaryOperation, _UnaryOperation)'
   47 | transform_reduce(_ExecutionPolicy&& __exec, _ForwardIterator __first, _ForwardIterator __last, _Tp __init,
      | ^~~~~~~~~~~~~~~~
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_numeric_defs.h:47:1: note:   template argument deduction/substitution failed:
In file included from ./common/formatting/tree_unwrapper.h:31,
                 from ./verilog/formatting/tree_unwrapper.h:26,
                 from verilog/formatting/tree_unwrapper.cc:15:
./common/util/tree_operations.h:729:56: note:   deduced conflicting types for parameter '_ForwardIterator' ('__gnu_cxx::__normal_iterator<verible::VectorTree<verible::UnwrappedLine>*, std::vector<verible::VectorTree<verible::UnwrappedLine>, std::allocator<verible::VectorTree<verible::UnwrappedLine> > > >' and 'int')
  729 |   const int grandchildren_count = std::transform_reduce(
      |                                   ~~~~~~~~~~~~~~~~~~~~~^
  730 |       node.Children().begin(), node.Children().end(), 0, std::plus<>(),
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  731 |       [](const T& gc) { return std::size(gc.Children()); });
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./common/formatting/tree_unwrapper.h:25,
                 from ./verilog/formatting/tree_unwrapper.h:26,
                 from verilog/formatting/tree_unwrapper.cc:15:
./common/text/concrete_syntax_tree.h: In member function 'bool verible::SyntaxTreeNode::MatchesTagAnyOf(std::initializer_list<_Tp>) const [with EnumType = verilog::NodeEnum]':

```

Just curious if anyone has run into this before or if I should even bother trying to build on CentOS 7.9.2009. It seems the binary releases work, but I was hoping to have the ability to modify the source code as needed. 

I suppose I can just use `verible-verilog-syntax` for anything that needs the AST. 

Feel free to close this if its a won't fix or unclear how to reproduce / what to investigate.
